name: pkgdown

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libxml2-dev libgsl-dev

      # This step creates a simple mock version of the cmdstanr package
      - name: Create mock cmdstanr package
        run: |
          mkdir -p R
          
          # Create a file to mock cmdstanr package
          cat > R/mock_cmdstanr.R << 'EOF'
          # Mock cmdstanr package
          .onLoad <- function(libname, pkgname) {
            message("Mock cmdstanr package loaded")
          }
          
          cmdstan_path <- function() {
            "/mock/cmdstan/path"
          }
          
          cmdstan_model <- function(...) {
            message("Mock cmdstan_model function called")
            list(
              sample = function(...) {
                message("Mock sample function called")
                list(
                  summary = function() {
                    data.frame(
                      parameter = c("mu", "sigma"),
                      mean = c(0, 1),
                      sd = c(0.1, 0.2)
                    )
                  }
                )
              }
            )
          }
          EOF
        shell: bash

      # Install BiocManager and rhdf5 early
      - name: Install BiocManager
        run: |
          install.packages("BiocManager")
          BiocManager::install("rhdf5")
        shell: Rscript {0}

      # Install remaining dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::pkgdown
            any::knitr
            any::rmarkdown
            any::ggrepel
            any::pheatmap
          needs: website

      # Add a note about cmdstanr to documentation
      - name: Create documentation note
        run: |
          mkdir -p vignettes
          echo "---" > vignettes/stan_note.Rmd
          echo "title: \"Note About Stan Dependencies\"" >> vignettes/stan_note.Rmd
          echo "output: rmarkdown::html_vignette" >> vignettes/stan_note.Rmd
          echo "vignette: >" >> vignettes/stan_note.Rmd
          echo "  %\\VignetteIndexEntry{Note About Stan Dependencies}" >> vignettes/stan_note.Rmd
          echo "  %\\VignetteEngine{knitr::rmarkdown}" >> vignettes/stan_note.Rmd
          echo "  %\\VignetteEncoding{UTF-8}" >> vignettes/stan_note.Rmd
          echo "---" >> vignettes/stan_note.Rmd
          echo "" >> vignettes/stan_note.Rmd
          echo "## Important: Stan Dependencies" >> vignettes/stan_note.Rmd
          echo "" >> vignettes/stan_note.Rmd
          echo "This documentation site was built without cmdstanr. The package will use rstan as the default backend." >> vignettes/stan_note.Rmd
          echo "" >> vignettes/stan_note.Rmd
          echo "For optimal performance with the TrajConserve package, you can install cmdstanr and set up your environment correctly." >> vignettes/stan_note.Rmd
          echo "" >> vignettes/stan_note.Rmd
          echo "Please refer to the [README](https://github.com/GilbertHan1011/TrajConserve) for complete installation instructions, especially the section on Stan Setup." >> vignettes/stan_note.Rmd
        shell: bash

      # Install the local package without Stan
      - name: Install package
        run: |
          install.packages(".", repos = NULL, type = "source")
        shell: Rscript {0}

      - name: Build pkgdown site
        run: |
          pkgdown::build_site()
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs 