name: pkgdown

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      # Add environment variables to prevent cmdstanr path issues
      R_CMDSTANR_PATH: "/home/runner/.cmdstan"
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libxml2-dev libgsl-dev
          
      - name: Set up C++ compilation for Stan
        run: |
          mkdir -p ~/.R
          echo 'CXX14 = g++' >> ~/.R/Makevars
          echo 'CXX17 = g++' >> ~/.R/Makevars
          echo 'CXX14FLAGS = -O3 -march=native -mtune=native -fPIC' >> ~/.R/Makevars
          echo 'CXX17FLAGS = -O3 -march=native -mtune=native -fPIC' >> ~/.R/Makevars
          echo 'STAN_CXX17 = TRUE' >> ~/.R/Makevars
          echo 'STAN_HAS_CXX17 = TRUE' >> ~/.R/Makevars
          echo 'TBB_CXX_TYPE = gcc' >> ~/.R/Makevars
          mkdir -p ~/.cmdstan/make
          echo 'STAN_HAS_CXX17 = true' >> ~/.cmdstan/make/local
          echo 'TBB_CXX_TYPE = gcc' >> ~/.cmdstan/make/local

      # Install BiocManager and rhdf5 early
      - name: Install BiocManager
        run: |
          install.packages("BiocManager")
          BiocManager::install("rhdf5")
        shell: Rscript {0}

      # Completely revised cmdstanr installation approach
      - name: Install cmdstanr with fixed version
        run: |
          install.packages("remotes")
          # Using a specific stable version of cmdstanr (0.5.3) instead of the development version
          remotes::install_github("stan-dev/cmdstanr@v0.5.3", upgrade = "never")
          # Create required directories 
          dir.create(Sys.getenv("R_CMDSTANR_PATH", "/home/runner/.cmdstan"), showWarnings = FALSE, recursive = TRUE)
          # Check if cmdstan is available and install with simplified options
          if (!cmdstanr::cmdstan_path_exists()) {
            cmdstanr::install_cmdstan(dir = Sys.getenv("R_CMDSTANR_PATH", "/home/runner/.cmdstan"), 
                                      cores = 2, 
                                      quiet = TRUE,
                                      overwrite = TRUE)
          }
        shell: Rscript {0}

      # Install remaining dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::pkgdown
            any::knitr
            any::rmarkdown
            any::ggrepel
            any::pheatmap
            local::.
          needs: website

      - name: Build pkgdown site
        run: |
          pkgdown::build_site()
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs 