name: pkgdown

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libxml2-dev libgsl-dev

      # Install dependencies manually
      - name: Install dependencies
        run: |
          # Install BiocManager
          install.packages("BiocManager")
          
          # Install packages from CRAN
          install.packages(c(
            "pkgdown", 
            "knitr", 
            "rmarkdown", 
            "ggrepel", 
            "pheatmap",
            "brms",
            "ggplot2",
            "gridExtra",
            "dplyr",
            "foreach",
            "doParallel",
            "progressr",
            "data.table",
            "tools",
            "rstan"
          ))
          
          # Install packages from Bioconductor
          BiocManager::install("rhdf5")
          
          # Install Seurat
          install.packages("Seurat")
        shell: Rscript {0}

      # Add a note about cmdstanr to documentation
      - name: Create documentation note
        run: |
          mkdir -p vignettes
          echo "---" > vignettes/stan_note.Rmd
          echo "title: \"Note About Stan Dependencies\"" >> vignettes/stan_note.Rmd
          echo "output: rmarkdown::html_vignette" >> vignettes/stan_note.Rmd
          echo "vignette: >" >> vignettes/stan_note.Rmd
          echo "  %\\VignetteIndexEntry{Note About Stan Dependencies}" >> vignettes/stan_note.Rmd
          echo "  %\\VignetteEngine{knitr::rmarkdown}" >> vignettes/stan_note.Rmd
          echo "  %\\VignetteEncoding{UTF-8}" >> vignettes/stan_note.Rmd
          echo "---" >> vignettes/stan_note.Rmd
          echo "" >> vignettes/stan_note.Rmd
          echo "## Important: Stan Dependencies" >> vignettes/stan_note.Rmd
          echo "" >> vignettes/stan_note.Rmd
          echo "This documentation site was built without cmdstanr. The package will use rstan as the default backend." >> vignettes/stan_note.Rmd
          echo "" >> vignettes/stan_note.Rmd
          echo "For optimal performance with the TrajConserve package, you can install cmdstanr and set up your environment correctly." >> vignettes/stan_note.Rmd
          echo "" >> vignettes/stan_note.Rmd
          echo "Please refer to the [README](https://github.com/GilbertHan1011/TrajConserve) for complete installation instructions, especially the section on Stan Setup." >> vignettes/stan_note.Rmd
        shell: bash

      # Build and install the package using R CMD methods
      - name: Build and install package
        run: |
          # Build the package tarball
          R CMD build .
          
          # Get the tarball filename
          PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
          
          # Install the built package
          install.packages(PKG_TARBALL, repos = NULL, type = "source")
          
          # Verify installation
          library(TrajConserve)
          packageVersion("TrajConserve")
        shell: Rscript {0}

      - name: Build pkgdown site
        run: |
          pkgdown::build_site()
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs 